# -*- coding: utf-8 -*-
"""41. Matrix Multiplication.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wSpBTGJB-bRcRZOSIuoMr91ocgZJGpCM
"""

def matrix_multiply(A, B):
    result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
    return result

if __name__ == "__main__":
    A = [[1, 2, 3], [4, 5, 6]]
    B = [[7, 8], [9, 10], [11, 12]]
    result = matrix_multiply(A, B)
    print("Resultant Matrix:")
    for row in result:
        print(row)