# -*- coding: utf-8 -*-
"""addition2numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RJjzzhZDnorZeI5nqTnPVU33UQKx6tiO
"""

a=int(input("enter 1st number:"))
b=int(input("enter 2nd number:"))
sum=a+b
print(sum)

a=float(input("enter 1st number:"))
b=float(input("enter 2nd number:"))
product=a*b
print(product)
