# -*- coding: utf-8 -*-
"""Adult.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z5Yih_nOzDHmRjU7z5pWduvtRfmQnTY6

to identify adult or minor
"""

age=int(input("enter age:"))
if age<0:
   print("error")
elif age<18:
   print("minor")
else:
   print("adult")