# -*- coding: utf-8 -*-
"""AI-Driven Haiku Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oec3zmoO53LxBMR95lfutkmIsyC7iVej

AI-Driven Haiku Generator
"""

import random

def generate_haiku(theme):
    # Haiku structure: 5 syllables, 7 syllables, 5 syllables
    haiku_5_syllables = [
        f"{theme} whispers soft",
        "Golden leaves falling",
        "Morning dew sparkles",
        "Shadows stretch with grace",
    ]
    haiku_7_syllables = [
        f"Underneath the open sky",
        "Echoes of time softly fade",
        "A gentle breeze carries hope",
        "Stars align to show the way",
    ]

    # Generate Haiku
    line1 = random.choice(haiku_5_syllables)
    line2 = random.choice(haiku_7_syllables)
    line3 = random.choice(haiku_5_syllables)

    return f"{line1}\n{line2}\n{line3}"

# User input for theme
theme = input("Enter a theme for your Haiku (e.g., nature, love, peace): ").strip()
print("\nHere is your AI-generated Haiku:\n")
print(generate_haiku(theme))