# -*- coding: utf-8 -*-
"""Alarm Clock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xTA12Gve5-nVg_CfsNuyWEuGpkT-i4Rm
"""

import time
from datetime import datetime

def set_alarm(alarm_time):
    print(f"Alarm set for {alarm_time}.")
    while True:
        now = datetime.now().strftime("%H:%M:%S")
        if now == alarm_time:
            print("Wake up! It's time!")
            break
        time.sleep(1)

if __name__ == "__main__":
    alarm_time = input("Enter the alarm time in HH:MM:SS format: ")
    set_alarm(alarm_time)