# -*- coding: utf-8 -*-
"""anagram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z9y40AcbnSBpaFPl3F1inOSQyn4WjDjc

**Check if a String is an Anagram**
"""

str1 = input("Enter first string: ").lower()
str2 = input("Enter second string: ").lower()
if sorted(str1) == sorted(str2):
    print("Anagram")
else:
    print("Not an Anagram")

str1 = input("Enter first string: ").lower()
str2 = input("Enter second string: ").lower()
if sorted(str1) == sorted(str2):
    print("Anagram")
else:
    print("Not an Anagram")