# -*- coding: utf-8 -*-
"""angle1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RxqhF0aQYi9UTrYHbStYrcRg6b3XHSal

Find the angle between the curves r = 4(1+cost) and r = 5(1−cost)
"""

from sympy import *
 r,t =symbols('r,t') # Define the variables required as symbols
 r1=4*(1+cos(t)); #Input first polar curve
 r2=5*(1-cos(t)); #Input first polar curve
 dr1=diff(r1,t) # find the derivative of first function
 dr2=diff(r2,t) # find the derivative of secodn function
 t1=r1/dr1
 t2=r2/dr2
 q=solve(r1-r2,t) # solve r1==r2, to find the point of intersectionbetween curves
 w1=t1.subs({t:float(q[1])}) # substitute the value of "t" in t1
 w2=t2.subs({t:float(q[1])}) # substitute the value of "t" in t2
 y1=atan(w1)
 # to find the inverse tan of w1
 y2=atan(w2) # to find the inverse tan of w2
 w=abs(y1-y2) # angle between two curves is abs(w1-w2)
 print('Angle between curves in radians is %0.3f'%(w))