# -*- coding: utf-8 -*-
"""append.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xHxy4R28ygOQqxvtpOdmkAh8tdoCb8hf

append to a file
"""

file=open("/content/example.txt","a")
file.write("this is an append line.\n")
file.close()