# -*- coding: utf-8 -*-
"""areaofcircle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eM7PWe2InXTHl6xIlG1GVteJuu7bKA78
"""

radius=float(input("enter the radius"))
pi=3.14
area=pi*radius**2
print("area of circle is:",area)