# -*- coding: utf-8 -*-
"""area and perimeter of rectangle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BpCb7YzOvZuq-P72nCbldGayIAZT1st_

calculate area and perimeter of rectangle
"""



66
length = float(input("Enter the length of the rectangle: "))
width = float(input("Enter the width of the rectangle: "))

area = length * width
perimeter = 2 * (length + width)

print("Area of the rectangle:", area)
print("Perimeter of the rectangle:", perimeter)