# -*- coding: utf-8 -*-
"""Arithmetic Progression:.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EYhqrh_mflvvqsFsC3sRj7Eb3Gcri_U2
"""

def arithmetic_progression(a, d, n):
    return [a + d * i for i in range(n)]

# Example usage
a = int(input("Enter the first term: "))
d = int(input("Enter the common difference: "))
n = int(input("Enter the number of terms: "))
print(f"Arithmetic Progression: {arithmetic_progression(a, d, n)}")