# -*- coding: utf-8 -*-
"""arithmetic operations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N-0jEtovyN_OtZxQbUib-ACfxIYIWKdn
"""

a=int(input("enter a number"))
b=int(input("enter a number"))
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)
print(a%b)