# -*- coding: utf-8 -*-
"""asciivalue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D7wZlB4f7vUS-_JIjPI12RM8OCWw01v9

**Find ASCII Value of a Character**
"""

char = input("Enter a character: ")
print("ASCII value of", char, "is", ord(char))