# -*- coding: utf-8 -*-
"""Bar Graph of Heights of Students.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_j6TNzxHaU4L1IGCg42U-wtgnOCkc7xo
"""

import matplotlib.pyplot as plt

def draw_height_bar_graph():
    # Data: Names of students and their heights (in cm)
    students = ['Alice', 'Bob', 'Charlie', 'David', 'Eve']
    heights = [150, 160, 165, 170, 155]

    # Create a bar chart
    plt.bar(students, heights, color='skyblue')

    # Adding title and labels
    plt.title("Height of Students")
    plt.xlabel("Students")
    plt.ylabel("Height (cm)")

    # Show the graph
    plt.show()

if __name__ == "__main__":
    draw_height_bar_graph()