# -*- coding: utf-8 -*-
"""Binary Search Algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d9xyXo9Fb3pdVuPPqaLHX_N7FXPQiExm
"""

def binary_search(arr, target):
    low, high = 0, len(arr) - 1
    while low <= high:
        mid = (low + high) // 2
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            low = mid + 1
        else:
            high = mid - 1
    return -1

if __name__ == "__main__":
    arr = [int(x) for x in input("Enter a sorted list of numbers separated by space: ").split()]
    target = int(input("Enter the number to search for: "))
    result = binary_search(arr, target)
    if result != -1:
        print(f"Element found at index {result}.")
    else:
        print("Element not found.")