# -*- coding: utf-8 -*-
"""binarytodecimal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t3G0ZCj0G8rkZMxQoilPDifWC4W92jeq

**binary to decimal conversion**
"""

binary = input("Enter a binary number: ")
decimal = int(binary, 2)
print("Decimal value:", decimal)