# -*- coding: utf-8 -*-
"""binarycoversion2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_X45qwj06ZufvidVsxI6vFgwBC8bSmHE
"""

def decimal_to_hexadecimal(decimal):
    return hex(decimal)[2:]

if __name__ == "__main__":
    decimal = int(input("Enter a decimal number: "))
    print(f"Hexadecimal: {decimal_to_hexadecimal(decimal)}")