# -*- coding: utf-8 -*-
"""binomial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ETS2FBaMe7DQ0ASTFvrWAT7lxAu5rj7v

Binomial Coefficient
"""

def fact(num):
   if num == 0:
      return 1
   else:
      return num * fact(num-1)
n = int(input("Enter the value of N : "))
r = int(input("Enter the value of R (R cannot be negative or greater than N): "))
nCr = fact(n)/(fact(r)*fact(n-r))
print(n,'C',r," = ","%d"%nCr,sep="")