# -*- coding: utf-8 -*-
"""bmi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YUvlKz84_UHrGF_FvboqQzfstGbdwA0K

BMI Calculator
"""

# Input weight and height
weight = float(input("Enter your weight in kilograms: "))
height = float(input("Enter your height in meters: "))

# Calculate BMI
bmi = weight / (height ** 2)

# Determine category
if bmi < 18.5:
    category = "underweight"
elif 18.5 <= bmi < 24.9:
    category = "normal weight"
elif 25 <= bmi < 29.9:
    category = "overweight"
else:
    category = "obesity"

# Print the result
print(f"Your BMI is {bmi:.2f}. You are categorized as {category}.")