# -*- coding: utf-8 -*-
"""Cardioid: r = 5(1+cosθ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uB-U7qCp2wgpy4ROY5Hq5K8RlcmeKJ0g
"""

#Plot cardioid r=5(1+cos theta)
 from pylab import *
 theta=linspace(0,2*np.pi,1000)
 r1=5+5*cos(theta)
 polar(theta,r1,'r')
 show()