# -*- coding: utf-8 -*-
"""Chaos Game (Sierpiński Triangle).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SYsklFq7fyYvBNeHBkFRU1wdCKHEGaf5
"""

import matplotlib.pyplot as plt
import random

def chaos_game(iterations):
    # Define the vertices of the triangle
    vertices = [(0, 0), (1, 0), (0.5, 0.866)]
    x, y = [0.5], [0.5]  # Starting point inside the triangle

    for _ in range(iterations):
        vertex = random.choice(vertices)
        x.append((x[-1] + vertex[0]) / 2)
        y.append((y[-1] + vertex[1]) / 2)

    plt.scatter(x, y, s=0.1, color='blue')
    plt.axis('off')
    plt.title("Sierpiński Triangle")
    plt.show()

# Example usage
iterations = int(input("Enter the number of iterations: "))
chaos_game(iterations)