# -*- coding: utf-8 -*-
"""circle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V5gsWDiW65QC8FBMT5GN2cmQxi7EyQ_O

Circle: x2 +y2 = 5
"""

# importing Sympy package with plot_implicit, symbols and Eq functionsonly
 # symbols: used to declare variable as symbolic expression
 # Eq: sets up an equation. Ex: 2x-y=0 is written as Eq(2*x-y,0)
from sympy import plot_implicit, symbols, Eq
x, y = symbols('x y')
p1 = plot_implicit(Eq(x**2 + y**2, 4),(x,-4,4),(y,-4,4),
title= 'Circle: $x^2+y^2=4$') # r= 2