# -*- coding: utf-8 -*-
"""circle2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TWU2rEZQYrpD2T_MFCaF7UlBG_z4Aawx
"""

import numpy as np
 import matplotlib.pyplot as plt
 plt.axes(projection = 'polar')
 r = 3
 rads = np.arange(0, (2 * np.pi), 0.01)
  # plotting the circle
 for i in rads:
   plt.polar(i, r, 'g.')
plt.show()