# -*- coding: utf-8 -*-
"""combininglists.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RxJnyve0nTzSvs13tuUKK3GPQkrkkglD

Merging two lists
"""

list1=[1,2,3]
list2=[4,5,6]
merged_list=list1+list2
print("merged_list:",merged_list)