# -*- coding: utf-8 -*-
"""Complex Number Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T-k8QmbjgQ7kZjhABJQH3Z8dmnNqELsD
"""

def complex_calculator():
    real1, imag1 = map(float, input("Enter real and imaginary part of the first complex number: ").split())
    real2, imag2 = map(float, input("Enter real and imaginary part of the second complex number: ").split())

    c1 = complex(real1, imag1)
    c2 = complex(real2, imag2)

    print(f"Addition: {c1 + c2}")
    print(f"Subtraction: {c1 - c2}")
    print(f"Multiplication: {c1 * c2}")
    print(f"Division: {c1 / c2 if c2 != 0 else 'Undefined'}")

complex_calculator()