# -*- coding: utf-8 -*-
"""countupper&lower.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mi7QuajQlQqnuYoGFx3w6vqPFR2etNqu

Count Uppercase and Lowercase Letters
"""

# Input from the user
text = input("Enter a string: ")

# Count uppercase and lowercase letters
uppercase_count = sum(1 for char in text if char.isupper())
lowercase_count = sum(1 for char in text if char.islower())

# Print the result
print(f"Uppercase letters: {uppercase_count}, Lowercase letters: {lowercase_count}")