# -*- coding: utf-8 -*-
"""Countdown Timer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eOlK3PhdVTzJ_p8Ek0lWZu5HPGgoqlkk
"""

import time

def countdown_timer(seconds):
    while seconds:
        mins, secs = divmod(seconds, 60)
        time_format = f"{mins:02}:{secs:02}"
        print(time_format, end="\r")
        time.sleep(1)
        seconds -= 1
    print("Time's up!")

if __name__ == "__main__":
    seconds = int(input("Enter the countdown time in seconds: "))
    countdown_timer(seconds)