# -*- coding: utf-8 -*-
"""Creative Coding: 3D Object Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U7KxrhpBky5CcpIrVLjHQaNcFborfTQM

Creative Coding: 3D Object Generator
"""

import numpy as np
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

def create_3d_object():
    phi = np.linspace(0, 2 * np.pi, 50)
    theta = np.linspace(0, np.pi, 50)
    phi, theta = np.meshgrid(phi, theta)

    # Define the 3D object (sphere)
    x = np.sin(theta) * np.cos(phi)
    y = np.sin(theta) * np.sin(phi)
    z = np.cos(theta)

    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    ax.plot_surface(x, y, z, cmap="plasma")
    plt.show()

create_3d_object()