# -*- coding: utf-8 -*-
"""Create a Scatter Plot Using Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vU75b-1xq8sMer0kK7woP5biNp_xPjlp
"""

import matplotlib.pyplot as plt

def draw_scatter_plot():
    x = [1, 2, 3, 4, 5]
    y = [5, 4, 3, 2, 1]

    plt.scatter(x, y)
    plt.title("Scatter Plot Example")
    plt.xlabel("X Axis")
    plt.ylabel("Y Axis")
    plt.show()

if __name__ == "__main__":
    draw_scatter_plot()