# -*- coding: utf-8 -*-
"""Currentdateandtime.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z05OnNjLWXhxOGj8xqUjpGrCuYP9Vrxp
"""

import datetime
now = datetime.datetime.now()
print("Current date and time:", now)