# -*- coding: utf-8 -*-
"""curves.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ahpkkLDWJAnaof6r7JQk_f--OVESRxYn

** 2D plots of cultivation and polar curves**

**sine and cosine curves**
"""

import numpy as np
import matplotlib.pyplot as plt

x=np.arange(-10,10,0.1)
y1=np.sin(x)
y2=np.cos(x)
plt.plot(x,y1,x,y2)

plt.title("sine curve and cosine curve")
plt.xlabel("value of x")
plt.ylabel("value of sin(x) and cos(x)")
plt.grid()
plt.show()