# -*- coding: utf-8 -*-
"""Customizable Dice Roller.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xSbT-WSUCO5HmbFSJ4M5BgIqna9rJuaI
"""

import random

def roll_dice(sides, rolls):
    for i in range(rolls):
        result = random.randint(1, sides)
        print(f"Roll {i + 1}: {result}")

if __name__ == "__main__":
    sides = int(input("Enter the number of sides on the dice: "))
    rolls = int(input("Enter the number of rolls: "))
    roll_dice(sides, rolls)