# -*- coding: utf-8 -*-
"""custom.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aFLYqQCn84TwOh01ii1jg5WDfE33LNdY

custom module
"""

def greet(name):
    return f"hello,{name}!"
def add(a,b):
    return a+b
greet("alice")
add(5,7)