# -*- coding: utf-8 -*-
"""Diamond.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hT84Jxlznkp_VZeCKwM1mtufgkFEGzbq

print a diamond pattern
"""

n = int(input("Enter number of rows: "))
for i in range(1, n + 1):
    print(" " * (n - i) + "*" * (2 * i - 1))
for i in range(n - 1, 0, -1):
    print