# -*- coding: utf-8 -*-
"""diceroll.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lon-BQVGsga9LNLklvvVyD9Em-mUVBw1

**Simulate a Dice Roll**
"""

import random
print("You rolled:", random.randint(1, 6))