# -*- coding: utf-8 -*-
"""dictionary1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v_saIlGBbo8D5t0C4in6AutqBW0ILxgk
"""

a={(1,2):1,(2,3):2}
print(a[1,2])