# -*- coding: utf-8 -*-
"""dictionary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qeA4I63yk0Brgzbmp32PHlWmHWT21EIz

Dictionary

Creating a dictionary
"""

student={"name":"alice","age":20,"marks":85}
student

"""Accessing and modifying items

Accessing
"""

print(student["name"])

"""Modifying"""

student["age"]=21
student

"""adding"""

student["grade"]="A"
student

"""removing"""

student={"name":"alice","age":20,"marks":85}
del student["marks"]
student

"""Iterating through a dictionary"""

for key,value in student.items():
   print(key,value)