# -*- coding: utf-8 -*-
"""dictionary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mX6SQeMuoBQrQnb03O0O1MPoaHFQ6-yx
"""

def spiral(row, column, arr):
    rowStart = 0
    columnStart = 0

    while rowStart < row and columnStart < column:

        for i in range(rowStart, row):
            print(arr[i][columnStart], end=" ")

        columnStart += 1

        for i in range(columnStart, column):
            print(arr[row - 1][i], end=" ")

        row -= 1

        if rowStart < row:
            for i in range(row - 1, rowStart - 1, -1):
                print(arr[i][column - 1], end=" ")
            column -= 1

        if columnStart < column:
            for i in range(column - 1, columnStart - 1, -1):
                print(arr[rowStart][i], end=" ")
            rowStart += 1

matrix = [[1, 2, 3],
          [5, 6, 7],
          [9, 10, 11]]

row = 3
column = 3

spiral(row, column, matrix)

"""dictionary"""

my_dict={}
my_dict[1]="one"
my_dict[1.0]="float one"
my_dict[True]="boolean one"
print(my_dict)