# -*- coding: utf-8 -*-
"""Differential Equation Solver python Copy Edit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mk5rs7x75CdN_EojEoFNT06ixK0GgZgG
"""

from scipy.integrate import solve_ivp

def differential_eq(t, y):
    return -y + t  # Example: dy/dt = -y + t

def solve_ode():
    t_span = (0, 5)  # Time range
    y0 = [1]  # Initial condition
    solution = solve_ivp(differential_eq, t_span, y0, t_eval=np.linspace(0, 5, 100))
    plt.plot(solution.t, solution.y[0], label="y(t)")
    plt.xlabel("t")
    plt.ylabel("y")
    plt.legend()
    plt.show()

solve_ode()