# -*- coding: utf-8 -*-
"""digitalclock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MgxlEo7yKq-MH_diyRhDhOcFxZVVudfL
"""

!apt-get update
!apt-get install -y xvfb x11-utils

import os
os.environ['DISPLAY'] = ':99'  # Set the DISPLAY environment variable

# Start Xvfb in the background
!Xvfb :99 -screen 0 1024x768x24 &

# ... rest of your code ...
import tkinter as tk
from time import strftime

def update_time():
    current_time = strftime('%H:%M:%S')
    label.config(text=current_time)
    label.after(1000, update_time)

root = tk.Tk() # Tkinter window initialization should now work
root.title("Digital Clock")

label = tk.Label(root, font=("Arial", 80), bg="black", fg="white")
label.pack(anchor="center")

update_time()
root.mainloop()