# -*- coding: utf-8 -*-
"""Divideby3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SaD70B6wBfvvuvsOnpZPxoVDVbPSePv5

check a number is dividible by 3
"""

dvd=int(input("enter a number"))
if dvd/3:
    print("dvd is divisible by 3")
else:
    print("dvd is not divisible by 3")