# -*- coding: utf-8 -*-
"""Draw a Circle Using Pygame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i4vhcHUf9Q3E-om1_FuWykHlFSj6ntbs
"""

import pygame

def draw_circle():
    pygame.init()
    window = pygame.display.set_mode((400, 400))
    pygame.display.set_caption("Draw Circle")

    running = True
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
        window.fill((255, 255, 255))  # Fill background with white
        pygame.draw.circle(window, (255, 0, 0), (200, 200), 100)  # Red circle
        pygame.display.flip()  # Update display

    pygame.quit()

if __name__ == "__main__":
    draw_circle()