# -*- coding: utf-8 -*-
"""Draw a Bar Chart Using Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oxn9zz9IaVibi2Ig9zdo9x6DAaUYNAAE
"""

import matplotlib.pyplot as plt

def draw_bar_chart():
    categories = ['A', 'B', 'C', 'D']
    values = [23, 45, 56, 78]

    plt.bar(categories, values)
    plt.title("Bar Chart Example")
    plt.xlabel("Categories")
    plt.ylabel("Values")
    plt.show()

if __name__ == "__main__":
    draw_bar_chart()