# -*- coding: utf-8 -*-
"""Draw a Line Graph Using Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1THcr0-svEahMN_0t2eGKG1WFbKcOcxQr
"""

import matplotlib.pyplot as plt

def draw_line_graph():
    x = [1, 2, 3, 4, 5]
    y = [1, 4, 9, 16, 25]

    plt.plot(x, y)
    plt.title("Line Graph Example")
    plt.xlabel("X Axis")
    plt.ylabel("Y Axis")
    plt.show()

if __name__ == "__main__":
    draw_line_graph()