# -*- coding: utf-8 -*-
"""Draw a Square Using Pygame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18-PCJ_g8ZkTAFXWD7WThGHr7n6KydF28
"""

import pygame

def draw_square():
    pygame.init()
    window = pygame.display.set_mode((400, 400))
    pygame.display.set_caption("Draw Square")

    running = True
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
        window.fill((255, 255, 255))  # White background
        pygame.draw.rect(window, (0, 128, 0), (150, 150, 100, 100))  # Green square
        pygame.display.flip()

    pygame.quit()

if __name__ == "__main__":
    draw_square()