# -*- coding: utf-8 -*-
"""eigen1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vk2WysSmgLww0_VgHJPPxoWuW6mY-4Y3
"""

import numpy as np
I=np.array([[4,3,2],[1,4,1],[3,10,4]])
print("\n Given matrix: \n", I)
 #x=np.linalg.eigvals(I)
w,v = np.linalg.eig(I)
print("\n Eigen values: \n", w)
print("\n Eigen vectors: \n", v)
 ## To display one eigen value and correspondingeigen vector
print("Eigen value:\n ", w[0])
print("\n Corresponding Eigen vector :", v[:,0])