# -*- coding: utf-8 -*-
"""Email Validator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MjI-GvY3Ml9Rq6J2MqMFZuiTwnaJ71Tu
"""

import re

def validate_email(email):
    regex = r'^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
    if re.match(regex, email):
        print(f"{email} is a valid email address.")
    else:
        print(f"{email} is an invalid email address.")

if __name__ == "__main__":
    email = input("Enter an email address to validate: ")
    validate_email(email)