# -*- coding: utf-8 -*-
"""Encryption: Text Encryptor/Decryptor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1spuBeNIM1O0fq8iRrZoY2Nv2WDnO0xsx

Encryption: Text Encryptor/Decryptor
"""

def encrypt(text, key):
    encrypted = ''.join(chr((ord(char) + key - 32) % 95 + 32) for char in text)
    return encrypted

def decrypt(encrypted, key):
    decrypted = ''.join(chr((ord(char) - key - 32) % 95 + 32) for char in encrypted)
    return decrypted

text = input("Enter text to encrypt: ")
key = int(input("Enter a numeric key: "))
encrypted = encrypt(text, key)
decrypted = decrypt(encrypted, key)

print(f"Encrypted: {encrypted}")
print(f"Decrypted: {decrypted}")