# -*- coding: utf-8 -*-
"""errorhandling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QXWgVN_-X6kZZdqJSbqhKs1QpShrllSZ

error handling

try-except block
"""

try:
    num=int(input("enter a number:"))
    print(10/num)
except ZeroDivisionError:
    print("error:cannot divide by zero.")
except ValueError:
    print("error:invalid input.please enter a valid number.")