# -*- coding: utf-8 -*-
"""Exponential curve, y = ex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YEqN7CukQhNyrwhFivj1qlnbNlEJnzwC

Exponential curve, y = ex
"""

# importing the required modules
import numpy as np
import matplotlib.pyplot as plt
x = np.arange(-10, 10, 0.001) # x takes the values between-10 and 10with a step length of 0.001
y = np.exp(x) # Exponential function
plt.plot(x,y) # plotting the points
plt.title("Exponential curve ") # giving a title to the graph
plt.grid() # displaying the grid
plt.show() # shows the plot