# -*- coding: utf-8 -*-
"""filehandlingmodes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YUksKbvQ-XC2xNwFYcTODUF6ZEdkeywD

file handling modes
"""

with open("/content/2560px-A-Cat.jpg","rb") as file:
    data=file.read()