# -*- coding: utf-8 -*-
"""finallyblock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18oKPrzHjICMXR02cTAzlcr-7gn26d8pB

finally block
"""

try:
    file=open("example.txt","r")
except FileNotFoundError:
    print("file not found.")
finally:
    print("execution complete")