# -*- coding: utf-8 -*-
"""fizz&buzz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12avSZoOnvkFQshk2hhdFObtCJ5DqJCWn
"""

for i in range(1,21):
    if i%3==0:
       print("Fizz",end=" ")
    elif i%5==0:
        print("Buzz",end=" ")
    else:
        print(i,end=" ")