# -*- coding: utf-8 -*-
"""forloop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m74Qy0yjgjRAYOJeQnCorjQx1yHNNkLn
"""

for i in range(1,11):
    print(f"The Square of a {i} is {i**2}")

for i in range(10,0,-1):
    print(i)