# -*- coding: utf-8 -*-
"""Fractal Generator (Mandelbrot Set).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-lme-pTK4DsR5PUb29RnFkNPKfqVdl_c
"""

import numpy as np
import matplotlib.pyplot as plt

def mandelbrot(xmin, xmax, ymin, ymax, width, height, max_iter):
    x = np.linspace(xmin, xmax, width)
    y = np.linspace(ymin, ymax, height)
    X, Y = np.meshgrid(x, y)
    C = X + 1j * Y
    Z = np.zeros_like(C)
    mandelbrot_set = np.zeros(C.shape, dtype=int)

    for i in range(max_iter):
        mask = np.abs(Z) <= 2
        Z[mask] = Z[mask] ** 2 + C[mask]
        mandelbrot_set[mask] += 1

    return mandelbrot_set

# Example usage
mandelbrot_set = mandelbrot(-2, 1, -1.5, 1.5, 1000, 1000, 50)
plt.imshow(mandelbrot_set, extent=(-2, 1, -1.5, 1.5), cmap='hot')
plt.colorbar()
plt.title("Mandelbrot Set")
plt.show()