# -*- coding: utf-8 -*-
"""Frequency.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vswe8BBNPVbPElK8lBW73g4iEnxFG72K

frequency of each characters of string
"""

s = input("Enter a string: ")
freq = {}
for char in s:
    freq[char] = freq.get(char, 0) + 1
print(freq)