# -*- coding: utf-8 -*-
"""Game Development: Pong Clone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fdrU6BMwsUhutWEfNgutffgwTAX3YS9E

Game Development: Pong Clone
"""

import pygame
import sys

pygame.init()

# Screen and paddle settings
width, height = 800, 600
screen = pygame.display.set_mode((width, height))
pygame.display.set_caption("Pong Game")

# Ball, paddles
ball = pygame.Rect(width // 2, height // 2, 20, 20)
player = pygame.Rect(width - 20, height // 2 - 70, 10, 140)
opponent = pygame.Rect(10, height // 2 - 70, 10, 140)

ball_speed = [4, 4]
clock = pygame.time.Clock()

def move_ball():
    global ball_speed
    ball.x += ball_speed[0]
    ball.y += ball_speed[1]

    if ball.top <= 0 or ball.bottom >= height:
        ball_speed[1] = -ball_speed[1]

    if ball.left <= 0 or ball.right >= width:
        ball_speed[0] = -ball_speed[0]

def draw():
    screen.fill("black")
    pygame.draw.ellipse(screen, "white", ball)
    pygame.draw.rect(screen, "white", player)
    pygame.draw.rect(screen, "white", opponent)
    pygame.display.flip()

# Main loop
while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()

    move_ball()
    draw()
    clock.tick(60)