# -*- coding: utf-8 -*-
"""Gcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R1tB75gU0xFJy4xSEPfH3REqRbuCKE74

gcd of two numbers
"""

a, b = map(int, input("Enter two numbers: ").split())
while b:
    a, b = b, a % b
print("GCD:", a)