# -*- coding: utf-8 -*-
"""Geometric Progression:.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lMjxhseKCFAPBvzMAhM-PSBKq-sRI453
"""

def geometric_progression(a, r, n):
    return [a * (r ** i) for i in range(n)]

# Example usage
a = int(input("Enter the first term: "))
r = int(input("Enter the common ratio: "))
n = int(input("Enter the number of terms: "))
print(f"Geometric Progression: {geometric_progression(a, r, n)}")