# -*- coding: utf-8 -*-
"""If statement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RrMf8_Sh1X-LPZ2KNYA8UvWOOJivpoL
"""

Control flow and loops

"""If statement"""

age=18
if age>=18:
  print("you are eligible to vote")