# -*- coding: utf-8 -*-
"""Evenorodd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YPF-AJ9IDIqPBhR9YiKRE1s9HA-pHyAp
"""

num=int(input("enter a number: "))
if num%2==0:
    print("even number")
else:
    print("odd number")
