# -*- coding: utf-8 -*-
"""Invertedanglrtriangle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14nrEy3N9Z_8TaUpVbojVuFhhpgjiKBeI

print an inverted angled triangle
"""

n = int(input("Enter number of rows: "))
for i in range(n, 0, -1):
    print("*" * i)