# -*- coding: utf-8 -*-
"""isprime.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NRpFgSVxB6fVkAsj-YgSwVDVZDuKCUfj
"""

def is_prime(num):
    if num<=1:
       return False
    for i in range(2,int(num**0.5)+1):
       if num%i==0:
          return False
       return True
number=int(input("enter a number:"))
if is_prime(number):
   print(number,"is a prime number")
else:
   print(number,"is not a prime number")