# -*- coding: utf-8 -*-
"""jacobian2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PvZZwU3NUXSehM0E4YmRNScYIX9swhce

If u = x+3y2−z3, v = 4x2yz, w = 2z2−xy then prove that at (1,−1,0),J = 20
"""

from sympy import *
x,y,z=symbols('x,y,z')
u=x+3*y**2-z**3
v=4*x**2*y*z
w=2*z*z**2-x*y
dux=diff(u,x)
duy=diff(u,y)
duz=diff(u,z)
dvx=diff(v,x)
dvy=diff(v,y)
dvz=diff(v,z)
dwx=diff(w,x)
dwy=diff(w,y)
dwz=diff(w,z)
J=Matrix([[dux,duy,duz],[dvx,dvy,dvz],[dwx,dwy,dwz]]);
print("The Jacobian matrix is ")
display(J)
Jac=Determinant(J).doit()
print('\n\n J = \n')
display(Jac)
J1=J.subs([(x, 1), (y,-1), (z, 0)])
print('\n\n J at (1,-1,0):\n')