# -*- coding: utf-8 -*-
"""Lemniscate: a2y2 = x2(a2 −x2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jUKw7Cc2wDTe75K40B2tS8guERVLMka9
"""

from sympy import plot_implicit, Eq, symbols

# Define symbols
x, y = symbols('x y')

# Create the plot
p5 = plot_implicit(
    Eq(4*(y**2), (x**2)*(4-x**2)),
    (x, -5, 5),
    (y, -5, 5)
)