# -*- coding: utf-8 -*-
"""lengthofstringwithoutlen().ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11MEsxpg9Jx3pcC1dsK-D25yoEKa_LplN

Find the Length of a String Without Using len()
"""

# Input from the user
string = input("Enter a string: ")

# Calculate length manually
length = 0
for char in string:
    length += 1

# Print the result
print(f"The length of the string is: {length}")