# -*- coding: utf-8 -*-
"""list1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16R8_gtUuidlC8GHpiEQLy-mltl7LNUqc
"""

a=[1,2,3,4,5,6,7,8,9]
print(a[::2])

a=[1,2,3,4,5,6,7,8,9]
print(a[::2])