# -*- coding: utf-8 -*-
"""list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LkDCCewY-PWl6BP6d56xRQFcEJhp08uR

list

creating a list
"""

numbers=[1,2,3,4,5]
numbers

mixed=[1,"hello",3.14]
mixed

"""list operations

accessing items
"""

print(numbers[0])

print(numbers[-1])

numbers[0]=10
numbers

numbers.append(6)
numbers

numbers.insert(1,15)
numbers

numbers.remove(2)
numbers

numbers.pop(2)
numbers

"""len()"""

len(numbers)

"""sort"""

numbers.sort()
numbers

"""reverse"""

numbers.sort()
numbers.reverse()
numbers

"""iterating through a list"""

for num in numbers:
   print(num)