# -*- coding: utf-8 -*-
"""list5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J6ckUrblUZoiHhvxfLXzinB6VukwZOO1
"""

arr=[1,2,3,4,5,6]
for i in range(1,6):
    arr[i-1]=arr[i]
for i in range(0,6):
    print(arr[i],end=" ")