# -*- coding: utf-8 -*-
"""list3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LQfAgpaDHHWo41wDWuD30JcDP8-sQtmX
"""

arr=[[1,2,3,4],
     [4,5,6,7],
     [8,9,10,11],
     [12,13,14,15]]
for i in range(0,4):
    print(arr[i].pop())