# -*- coding: utf-8 -*-
"""list4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mq5MQu1PY7HGvX10LCE5AvQbGwE6HHcl
"""

def f(i,values=[]):
    values.append(i)
    print(values)
    return values
f(1)
f(2)
f(3)