# -*- coding: utf-8 -*-
"""listtodictionary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KXcKRKq7nMmJ41m4LSOD3H8MwxWuHu0_

two list to dictionary
"""

# Input two lists
keys = input("Enter a list of keys separated by space: ").split()
values = list(map(int, input("Enter a list of values separated by space: ").split()))

# Create a dictionary
dictionary = dict(zip(keys, values))

# Print the result
print(f"The dictionary is: {dictionary}")