# -*- coding: utf-8 -*-
"""List of Square Numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MSTSiLaLulKu4YEH0OY4_R69Efhd_m2b
"""

def generate_squares(n):
    return [x**2 for x in range(1, n+1)]

if __name__ == "__main__":
    n = int(input("Enter the value of n: "))
    print(f"List of square numbers from 1 to {n}: {generate_squares(n)}")