# -*- coding: utf-8 -*-
"""mathmodule.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HbZ4w4GvPs3ZMcLzNKZ016gn7-KDZX5F

use the math module to solve a problem
"""

import math

angle=float(input("enter an angle in degrees:"))
radian=math.radians(angle)
print("sine of the angle:",math.sin(radian))
print("cosine of angle:",math.cos(radian))