# -*- coding: utf-8 -*-
"""maximum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NKhQoRGkmTGYscw9TACvVoPs_MAghACQ

find the maximum and minimum in a list
"""

numbers=[10,20,30,40,50]
print("maximum :",max(numbers))
print("minimum :",min(numbers))