# -*- coding: utf-8 -*-
"""maximaandminima.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VaofX2l8xQ-pEQvFhsK9_BhBgaxeZOsG

Find the Maxima and minima of f(x,y) = x2 +y2 +3x−3y+4
"""

import sympy
from sympy import Symbol, solve, Derivative, pprint

x = Symbol('x')
y = Symbol('y')
f = x**2 + x*y + y**2 + 3*x - 3*y + 4

d1 = Derivative(f, x).doit()
d2 = Derivative(f, y).doit()

criticalpoints = solve((d1, d2), (x, y)) # Solve the system of equations

# criticalpoints will now be a dictionary of solutions {x: value, y: value}
# Extract the values for x and y
x_critical = criticalpoints[x]
y_critical = criticalpoints[y]


s1 = Derivative(f, x, 2).doit()
s2 = Derivative(f, y, 2).doit()
s3 = Derivative(Derivative(f, y), x).doit()

print('function value is ')

# Substitute the critical values directly
q1 = s1.subs({x: x_critical, y: y_critical}).evalf()
q2 = s2.subs({x: x_critical, y: y_critical}).evalf()
q3 = s3.subs({x: x_critical, y: y_critical}).evalf()

delta = s1 * s2 - s3**2
print(delta, q1)

if delta > 0 and s1 < 0:
    print(" f takes maximum ")
elif delta > 0 and s1 > 0:
    print(" f takes minimum")
if delta < 0:
    print("The point is a saddle point")
if delta == 0:
    print("further tests required")