# -*- coding: utf-8 -*-
"""minutestohours.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BbSyBLhqH7u-GB6XZC0m0JajWQMf0wNg

convert minutes to hours and minutes
"""

minutes=int(input("enter minutes:"))
hours=minutes//60
remaining_minutes=minutes%60
print(f" time:{hours} hours and {remaining_minutes} minutes.")