# -*- coding: utf-8 -*-
"""missinglist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_3gdnAesqwyX2RoxUPSLbZ4qmVlFL9az

find the missing number in a list
"""

# Input a list of numbers from 1 to N, with one missing number
numbers = list(map(int, input("Enter a list of numbers separated by space: ").split()))

# Find the missing number
n = len(numbers) + 1
expected_sum = n * (n + 1) // 2
actual_sum = sum(numbers)
missing_number = expected_sum - actual_sum

# Print the result
print(f"The missing number is: {missing_number}")