# -*- coding: utf-8 -*-
"""Monte Carlo Simulation for π.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lyGwES6mPZzi9LudG2EC9qp9Mlvd9Laa
"""

import random

def monte_carlo_pi(num_points):
    inside_circle = 0
    for _ in range(num_points):
        x, y = random.random(), random.random()
        if x ** 2 + y ** 2 <= 1:
            inside_circle += 1
    return (4 * inside_circle) / num_points

# Example usage
points = int(input("Enter the number of points: "))
print(f"Estimated value of π: {monte_carlo_pi(points)}")