# -*- coding: utf-8 -*-
"""Morse Code Translator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tzwkuLgYuopl-hFIP18_w3l3OP8D-e6I
"""

MORSE_CODE_DICT = {
    'A': '.-', 'B': '-...', 'C': '-.-.', 'D': '-..', 'E': '.', 'F': '..-.',
    'G': '--.', 'H': '....', 'I': '..', 'J': '.---', 'K': '-.-', 'L': '.-..',
    'M': '--', 'N': '-.', 'O': '---', 'P': '.--.', 'Q': '--.-', 'R': '.-.',
    'S': '...', 'T': '-', 'U': '..-', 'V': '...-', 'W': '.--', 'X': '-..-',
    'Y': '-.--', 'Z': '--..', '1': '.----', '2': '..---', '3': '...--',
    '4': '....-', '5': '.....', '6': '-....', '7': '--...', '8': '---..',
    '9': '----.', '0': '-----', ' ': '/'
}

def text_to_morse(text):
    return ' '.join(MORSE_CODE_DICT[char] for char in text.upper())

def morse_to_text(morse):
    reverse_dict = {v: k for k, v in MORSE_CODE_DICT.items()}
    return ''.join(reverse_dict[code] for code in morse.split())

if __name__ == "__main__":
    choice = input("Choose: 1 for Text to Morse, 2 for Morse to Text: ")
    if choice == "1":
        text = input("Enter text: ")
        print(f"Morse Code: {text_to_morse(text)}")
    elif choice == "2":
        morse = input("Enter Morse code (separate with spaces): ")
        print(f"Text: {morse_to_text(morse)}")
    else:
        print("Invalid choice!")