# -*- coding: utf-8 -*-
"""multiplicationtable.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1olZDvT8sVQdBm9t7bERmz7c0qIa6_jI_

**print multiplication table**
"""

num = int(input("Enter a number: "))
for i in range(1, 11):
    print(f"{num} x {i} = {num * i}")