# -*- coding: utf-8 -*-
"""multiplicationcreator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16OLHIKhujMi0LMMR_9SMDQVleKzUH4e1
"""

num=int(input("Enter a number:"))
for i in range(1,11):
    print(f"{num} * {i} = {num*i}")