# -*- coding: utf-8 -*-
"""Numerical Integration (Simpson’s Rule.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cROW4bXNVQN7CXht8l84RQvd0WZasLBQ
"""

def f(x):
    return x ** 2  # Example function: f(x) = x^2

def simpsons_rule(a, b, n):
    if n % 2 == 1:
        n += 1  # n must be even
    h = (b - a) / n
    result = f(a) + f(b)
    for i in range(1, n):
        weight = 4 if i % 2 == 1 else 2
        result += weight * f(a + i * h)
    return (h / 3) * result

# Example usage
a, b = 0, 1  # Integration limits
n = int(input("Enter the number of intervals: "))
print(f"Integral result: {simpsons_rule(a, b, n)}")