# -*- coding: utf-8 -*-
"""openingfile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f4BKB-D4ah083LGp_bsyO2rqTNCRF2Mz

file operations

opening a file

file operations
"""

file=open("/content/drive/MyDrive/nithin.txt","r")