# -*- coding: utf-8 -*-
"""palindrome1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1blAZwoRG6Unb2Ce0LhJ2FQJHTTbG-FP0

palindrome1
"""

number=int(input("enter a number:"))
reverse_number=0
temp=number
while temp>0:
    digit=temp%10
    reverse_number=reverse_number*10+digit
    temp=temp//10
if number==reverse_number:
    print(f"{number}is a palindrome")
else:
    print(f"{number}is not a palindrome")