# -*- coding: utf-8 -*-
"""partialderivatives2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/112kPyu81eQoStLe0YyrPrt6_J0tYgLyx

2. Prove that if u = ex(xcos(y)−ysin(y)) then uxx +uyy = 0
"""

from sympy import *
 x,y =symbols('x y')
 u=exp(x)*(x*cos(y)-y*sin(y))
 display(u)
 dux=diff(u,x)
 duy=diff(u,y)
 uxx=diff(dux,x) # or uxx=diff(u,x,x) second derivative of u w.r.t x
 uyy=diff(duy,y) # or uyy=diff(u,y,y) second derivative of u w.r.t y
 w=uxx+uyy
 # Add uxx and uyy
 w1=simplify(w)
 # Simply the w to get actual result
 print('Ans:',float(w1))