# -*- coding: utf-8 -*-
"""pascalstriangle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qVvjINd0PmMw0wuACaGy2lAvZeGPZTeT

**Generate Pascal’s Triangle**
"""

n = int(input("Enter the number of rows: "))
triangle = [[1]]
for i in range(1, n):
    row = [1]
    for j in range(1, i):
        row.append(triangle[i - 1][j - 1] + triangle[i - 1][j])
    row.append(1)
    triangle.append(row)
for row in triangle:
    print(row)