# -*- coding: utf-8 -*-
"""perfectnumber.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yr3rQU98jkEPIcghAnzDCjfsZA1CEedZ

** Check Perfect Number**
"""

num = int(input("Enter a number: "))
divisors = [i for i in range(1, num) if num % i == 0]
if sum(divisors) == num:
    print("Perfect Number")
else:
    print("Not a Perfect Number")