# -*- coding: utf-8 -*-
"""Pi Approximation Using Leibniz Series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eHGNuiSXCl07xv-oU2hFYVlSNjOx7JO_
"""

def leibniz_pi(terms):
    pi_estimate = 0
    for k in range(terms):
        pi_estimate += (-1) ** k / (2 * k + 1)
    return 4 * pi_estimate

# Example usage
terms = int(input("Enter the number of terms: "))
print(f"Approximated value of π: {leibniz_pi(terms)}")