# -*- coding: utf-8 -*-
"""Polygon Area Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j3VjKcBISxibf47O6eVKnCGA9XOoHlgj
"""

def polygon_area(vertices):
    n = len(vertices)
    area = 0
    for i in range(n):
        x1, y1 = vertices[i]
        x2, y2 = vertices[(i + 1) % n]
        area += x1 * y2 - y1 * x2
    return abs(area) / 2

# Example usage
vertices = [(0, 0), (4, 0), (4, 3), (0, 3)]
print(f"Area of the polygon: {polygon_area(vertices)}")