# -*- coding: utf-8 -*-
"""Pomodoro Timer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I3CB0TjwLWV1O6G3HtSB-IG1wiC8Qw0j
"""

import time

def pomodoro_timer(work_minutes, break_minutes):
    print(f"Work for {work_minutes} minutes.")
    time.sleep(work_minutes * 60)
    print("Time's up! Take a break.")
    time.sleep(break_minutes * 60)
    print("Break over! Back to work.")

if __name__ == "__main__":
    work_minutes = int(input("Enter work duration in minutes: "))
    break_minutes = int(input("Enter break duration in minutes: "))
    pomodoro_timer(work_minutes, break_minutes)