# -*- coding: utf-8 -*-
"""powerwithout*.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kAQVx89ZLlFaI08XhpYjNHqQAc4hnDpP

**Calculate Power Without Using **
"""

base = int(input("Enter the base: "))
exponent = int(input("Enter the exponent: "))
result = 1
for _ in range(exponent):
    result *= base
print("Result:", result)