# -*- coding: utf-8 -*-
"""Prime Factorization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nhbFaheP5rtfR1ISJFzaKp76u_caNU6w
"""

def prime_factors(n):
    factors = []
    divisor = 2
    while n > 1:
        while n % divisor == 0:
            factors.append(divisor)
            n //= divisor
        divisor += 1
    return factors

# Example usage
number = int(input("Enter a number: "))
print(f"Prime factors of {number} are: {prime_factors(number)}")