# -*- coding: utf-8 -*-
"""print item(dictionary).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JyOiY9IS1Q2QUO5xKqOa3BLTuWjPbJnc

printing item in dictionary
"""

my_dict={1: 2, 2: 3, 3: 4}
x=my_dict[my_dict[1]]
print(x)