# -*- coding: utf-8 -*-
"""Pyramid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IxN00T1EySJp0cScYPhH8Wj8dC3C6c5s

print a pyramid pattern
"""

n = int(input("Enter number of rows: "))
for i in range(1, n + 1):
    print(" " * (n - i) + "*" * (2 * i-1))