# -*- coding: utf-8 -*-
"""radius2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zoXv0-JlZLUrs5_0ms13pAqYwws2UcyQ

Find the radius of curvature for r = asin(nt) at t = pi/2 and n = 1
"""

from sympy import *
t,r,a,n=symbols('t r a n')
r=a*sin(n*t)
r1=Derivative(r,t).doit()
r2=Derivative(r1,t).doit()
rho=(r**2+r1**2)**1.5/(r**2+2*r1**2-r*r2);
rho1=rho.subs(t,pi/2)
rho1=rho1.subs(n,1)
print("The radius of curvature is")
display(simplify(rho1))