# -*- coding: utf-8 -*-
"""radiusofcurvature.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SizjTENzTEh4CZ6tU_9Ed29XEYv_8hPY

Formula to calculate Radius of curvature in polar form is ρ = (r2 + r2
 1)3/2
 r2 +2r2
 1 − rr2

1. Find the radius of curvature, r = 4(1+cost) at t=π/2.
"""

from sympy import *
 t=Symbol('t') # define t as symbol
 r=Symbol('r')
 r=4*(1+cos(t))
 r1=Derivative(r,t).doit() #find the first derivative of r w.r.t "t"
 r2=Derivative(r1,t).doit() #find the second derivative of r w.r.t "t"
 rho=(r**2+r1**2)**(1.5)/(r**2+2*r1**2-r*r2); # Substitute r1 and r2 informula
 rho1=rho.subs(t,pi/2) # substitute t in rho
 print('The radius of curvature is %3.4f units'%rho1)