# -*- coding: utf-8 -*-
"""Random.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N-d7ElIrAsO-iD2Ylg6_BCtLJqF3LS__

Generator random numbers
"""

import random

# Generate a random number between 1 and 100
random_number = random.randint(1, 100)

print("Generated Random Number:", random_number)