# -*- coding: utf-8 -*-
"""random.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-BkLxL5z-jl0fc0cRNzRuxzlDYPc1pkV

random
"""

import random
random_number = random.randint(1,6)
print("the random_number is:",random_number)