# -*- coding: utf-8 -*-
"""Random Walk Simulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/185rPgBa_ttOTTobeBfOukzykIokQqS1z
"""

import random
import matplotlib.pyplot as plt

def random_walk(steps):
    x, y = [0], [0]
    for _ in range(steps):
        direction = random.choice(['up', 'down', 'left', 'right'])
        if direction == 'up':
            x.append(x[-1])
            y.append(y[-1] + 1)
        elif direction == 'down':
            x.append(x[-1])
            y.append(y[-1] - 1)
        elif direction == 'left':
            x.append(x[-1] - 1)
            y.append(y[-1])
        else:  # right
            x.append(x[-1] + 1)
            y.append(y[-1])
    return x, y

# Example usage
steps = int(input("Enter the number of steps: "))
x, y = random_walk(steps)
plt.plot(x, y, marker='o')
plt.title("Random Walk")
plt.show()