# -*- coding: utf-8 -*-
"""Random Name Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s1CXZgmmZcDp1WDyETN-TUpQYIpihlfb
"""

import random

def generate_random_name():
    first_names = ["John", "Emma", "Sophia", "Michael", "Olivia", "James", "Ava", "William", "Isabella", "Ethan"]
    last_names = ["Smith", "Johnson", "Brown", "Williams", "Jones", "Garcia", "Miller", "Davis", "Rodriguez", "Martinez"]

    first_name = random.choice(first_names)
    last_name = random.choice(last_names)
    return f"{first_name} {last_name}"

if __name__ == "__main__":
    print("Randomly Generated Name:", generate_random_name())