# -*- coding: utf-8 -*-
"""Rigthtangledtriangle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qp-zxvn0ZgdIxCduqL64OsYS7DLCc4_y

print a right angled triangle
"""

n = int(input("Enter number of rows: "))
for i in range(1, n + 1):
    print("*" * i)