# -*- coding: utf-8 -*-
"""rock,scissorgame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yM53zJXWtUbK3P-AYDJY5vo5IVXszmn9

Rock, Paper, Scissors Game
"""

import random

choices = ["rock", "paper", "scissors"]
user_choice = input("Choose rock, paper, or scissors: ").lower()
computer_choice = random.choice(choices)

# Determine the winner
if user_choice == computer_choice:
    print(f"Both chose {user_choice}. It's a tie!")
elif (user_choice == "rock" and computer_choice == "scissors") or \
     (user_choice == "paper" and computer_choice == "rock") or \
     (user_choice == "scissors" and computer_choice == "paper"):
    print(f"You chose {user_choice}, computer chose {computer_choice}. You win!")
else:
    print(f"You chose {user_choice}, computer chose {computer_choice}. You lose!")