# -*- coding: utf-8 -*-
"""rose.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1goK5bMQTApo2m0cabOU8FNdqV-SMcwqH

**four leaved rose**
"""

from pylab import *
theta=linspace(0,2*pi,1000)
r=2*abs(cos(2*theta))
polar(theta,r,'r')
show()