# -*- coding: utf-8 -*-
"""Scientific Computing: Simulate Virus Spread.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nFskAnQ94tsJGuMwFazlyAd5jq9kgcS2

Scientific Computing: Simulate Virus Spread
"""

import numpy as np
import matplotlib.pyplot as plt

def simulate_sir(population, beta, gamma, days):
    S, I, R = population - 1, 1, 0  # Initial values
    results = [(S, I, R)]

    for _ in range(days):
        new_infected = beta * S * I / population
        new_recovered = gamma * I
        S = S - new_infected
        I = I + new_infected - new_recovered
        R = R + new_recovered
        results.append((S, I, R))

    return np.array(results)

# Parameters
population = 1000
beta = 0.3  # Infection rate
gamma = 0.1  # Recovery rate
days = 100

results = simulate_sir(population, beta, gamma, days)
plt.plot(results[:, 0], label="Susceptible")
plt.plot(results[:, 1], label="Infected")
plt.plot(results[:, 2], label="Recovered")
plt.legend()
plt.xlabel("Days")
plt.ylabel("Population")
plt.title("SIR Model of Virus Spread")
plt.show()