# -*- coding: utf-8 -*-
"""secondlargestnumbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/117YJE2-TbtGb2BvgqrEDRr2vPVfeD77K

**Find Second Largest Number in a List**
"""

numbers = list(map(int, input("Enter numbers separated by space: ").split()))
unique_numbers = list(set(numbers))
unique_numbers.sort()
print("Second largest number is:", unique_numbers[-2])