# -*- coding: utf-8 -*-
"""selfsortingdictionary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/124AOPQ4yusOTE2R_DKLVZAJrwZSc_Xca

Self-Sorting Dictionary
"""

class AutoSortingDict:
    def __init__(self):
        self.data = {}

    def add(self, key, value):
        self.data[key] = value
        self.data = dict(sorted(self.data.items()))

    def display(self):
        for key, value in self.data.items():
            print(f"{key}: {value}")

# Test the AutoSortingDict
auto_dict = AutoSortingDict()
auto_dict.add("banana", 5)
auto_dict.add("apple", 2)
auto_dict.add("cherry", 10)

print("Auto-sorted dictionary:")
auto_dict.display()