# -*- coding: utf-8 -*-
"""set.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1odO4X7VbvXZN3g1UeySq2u39hxNgIVxz

set

creating a list
"""

numbers={1,2,3,4,5}
numbers

"""set operations

adding items
"""

numbers.add(6)
numbers

"""removing items"""

numbers.remove(3)
numbers

"""unions"""

set1={1,2,3}
set1
set2={3,4,5}
set2
set1|set2

"""intersection"""

set1&set2

"""difference"""

set1-set2

"""Manipulating a string"""

fruits=["apple","banana","cherry"]
fruits.append("orange")
fruits.remove("banana")
print(fruits)

"""Creating a dictionary"""

book={
    "title":"python basics",
    "author":"john doe",
    "year":2021

}
print(book["title"])
book["year"]=2022
print(book)

"""Merging two lists"""

list1=[1,2,3]
list2=[4,5,6]
merged_list=list1+list2
print("merged_list:",merged_list)