# -*- coding: utf-8 -*-
"""Simple Linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ts1dBLhs1_m0dOpBo2tacS4MlsHzyEWc
"""

import numpy as np

def linear_regression(x, y):
    n = len(x)
    m = (n * np.sum(x * y) - np.sum(x) * np.sum(y)) / (n * np.sum(x ** 2) - np.sum(x) ** 2)
    b = (np.sum(y) - m * np.sum(x)) / n
    return m, b

# Example usage
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 4, 5])
m, b = linear_regression(x, y)
print(f"Line of best fit: y = {m:.2f}x + {b:.2f}")