# -*- coding: utf-8 -*-
"""simplegraph.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o_WK1jl4ULZNxyfKBeZ3W-DGP_W9asm8
"""

# A simple graph
import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(0, 2, 100)
plt.plot(x, x, label='linear') # Plot of y=x a linear curve
plt.plot(x, x**2, label='quadratic') # Plot of y=x^2 a quadric curve
plt.plot(x, x**3, label='cubic') # Plot of y=x^3 a cubic curve
plt.xlabel('x label') # Add an x-label to the axes.
plt.ylabel('y label') # Add a y-label to the axes.
plt.title("Simple Plot") # Add a title to the axes.
plt.legend() # Add a legend
plt.show() # to show the complete graph