# -*- coding: utf-8 -*-
"""simple_interest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wtwIXClxVHmbHYwE66diMo6opIbNnqnw
"""

print("enter principle,rate of interest and time")
p=float(input())
r=float(input())
t=float(input())
si=(p*r*t)/100
print("simple interest is:",si)