# -*- coding: utf-8 -*-
"""simpletodolist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-81khls0NZWv1Dh2Ny9BaGGTHmk_uWE5

Create a Simple To-Do List
"""

# Create an empty list for tasks
tasks = []

# Display menu
while True:
    print("\nTo-Do List:")
    print("1. Add task")
    print("2. View tasks")
    print("3. Delete task")
    print("4. Exit")

    choice = input("Enter your choice: ")

    if choice == '1':
        task = input("Enter the task to add: ")
        tasks.append(task)
    elif choice == '2':
        print("Tasks in the list:")
        for idx, task in enumerate(tasks, 1):
            print(f"{idx}. {task}")
    elif choice == '3':
        task_num = int(input("Enter the task number to delete: "))
        if 1 <= task_num <= len(tasks):
            tasks.pop(task_num - 1)
            print("Task deleted.")
        else:
            print("Invalid task number.")
    elif choice == '4':
        break
    else:
        print("Invalid choice. Please try again.")