# -*- coding: utf-8 -*-
"""solarsystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JlVBTbM4fGbwzOvr2minbaP_Jh6r-4Iu

Simulations: Solar System Model
"""

import numpy as np
import matplotlib.pyplot as plt

def solar_system_simulation():
    t = np.linspace(0, 2 * np.pi, 100)
    sun = (0, 0)

    # Orbits
    earth_orbit = (np.cos(t) * 1, np.sin(t) * 1)
    mars_orbit = (np.cos(t) * 1.5, np.sin(t) * 1.5)

    plt.figure(figsize=(6, 6))
    plt.scatter(*sun, color="yellow", s=500, label="Sun")
    plt.plot(*earth_orbit, color="blue", label="Earth's Orbit")
    plt.plot(*mars_orbit, color="red", label="Mars' Orbit")

    plt.legend()
    plt.title("Simplified Solar System")
    plt.axis("equal")
    plt.show()

solar_system_simulation()