# -*- coding: utf-8 -*-
"""sortlist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bwQ6ktE-Z3vVn-7LzJLMh8LV51333N-j

sort a list of tuples by the second element
"""

tuples=[(1,"apples"),(2,"bananas"),(3,"cherries")]
sorted_tuples=sorted(tuples,key=lambda x:x[1])
print("sorted_tuples:",sorted_tuples)