# -*- coding: utf-8 -*-
"""sortlist27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YcrHNSqLUfdLlBulN260Wf58UnURRu9q

**Check if a List is Sorted**
"""

numbers = list(map(int, input("Enter numbers separated by space: ").split()))
if numbers == sorted(numbers):
    print("List is sorted")
else:
    print("List is not sorted")

numbers = list(map(int, input("Enter numbers separated by space: ").split()))
if numbers == sorted(numbers):
    print("List is sorted")
else:
    print("List is not sorted")