# -*- coding: utf-8 -*-
"""stringreverse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eWvGP9Wouaa_7PKNuEe4s_5S6KC8PKyI

Reverse a String
"""

string = input("Enter a string: ")
print("Reversed string:", string[::-1])