# -*- coding: utf-8 -*-
"""stringoflisttoupper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mdkq-D32up-HO5GrkRqEoCoBNUF-l9qa

converting a list to uppercase
"""

# Input a list of strings
strings = input("Enter a list of strings separated by space: ").split()

# Convert strings to uppercase
uppercase_strings = [string.upper() for string in strings]

# Print the result
print(f"The list of strings in uppercase: {uppercase_strings}")