# -*- coding: utf-8 -*-
"""strophoid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dShu8OBm9SS8Ym72McFBy4X8Uq485y9j
"""

from sympy import plot_implicit, Eq, symbols

x, y = symbols('x y') # Define x and y as symbols
p3= plot_implicit(
    Eq((y**2)*(2-x), (x**2)*(2+x)), (x,-5, 5), (y,-5, 5),
    title= 'Strophoid: $y^2 (a-x)=x^2 (a+x), a> 0$'
) # a=2