# -*- coding: utf-8 -*-
"""sumoflist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xh0Gec-3lfJklsGhk8b5qq8p3OqJA27c

**sum of a list**
"""

numbers = list(map(int, input("Enter numbers separated by space: ").split()))
print("Sum of the list:", sum(numbers))