# -*- coding: utf-8 -*-
"""Sumofalleven.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LaEqU_2NBL0_m-INgjCTCi-2vR7CWt0y

Sum of all even numbers in a range
"""

start=int(input("enter start of range:"))
end=int(input("enter end of range:"))
even_sum=0
for num in range(start,end+1):
    if num%2==0:
       even_sum+=num
    print("sum of even numbers:",even_sum)2