# -*- coding: utf-8 -*-
"""sumofsquares.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MZGcesBgGuBpe9xg0LEAl8HpCoVNkgzk

**Find the Sum of Squares of Numbers**
"""

n = int(input("Enter a number: "))
sum_of_squares = sum(i ** 2 for i in range(1, n + 1))
print("Sum of squares:", sum_of_squares)