# -*- coding: utf-8 -*-
"""sumofevenlist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A2nPZ471Q59nwCLkhV6G7oe-XVa8uu8D

sum of even numbers in a list
"""

# Input a list of numbers
numbers = list(map(int, input("Enter a list of numbers separated by space: ").split()))

# Sum of even numbers
even_sum = sum(num for num in numbers if num % 2 == 0)

# Print the result
print(f"The sum of even numbers in the list is: {even_sum}")