# -*- coding: utf-8 -*-
"""taylorandl'hospital.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c81W6QXatTU25EazGy82AjE0HQyy0LHO

**taylor series expansion**
"""

from sympy import Limit,Symbol,exp,sin
x=Symbol('x')
l=Limit((sin(x))/x,x,0).doit()
print(l)

"""**l' hospital's rule**"""

from sympy import *
from math import inf
x=Symbol('x')
l=Limit((1+1/x)**x,x,inf).doit()
display(l)