# -*- coding: utf-8 -*-
"""temperature.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rdohc-WD9zbKsqBiPB5Hgbg6miYzQ2BH

temperature converter
"""

celsius=float(input("enter temperature in celsius:"))
fahrenheit=(celsius*9/5)+32
print("temperature in fahrenheit:",fahrenheit)