# -*- coding: utf-8 -*-
"""timeconversion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RDtgnLRtpUwJmykyvUc1lu3gINsDQ43c

Convert Time (Seconds to H:M:S)
"""

# Input time in seconds
seconds = int(input("Enter time in seconds: "))

# Convert to hours, minutes, and seconds
hours = seconds // 3600
minutes = (seconds % 3600) // 60
remaining_seconds = seconds % 60

# Print the result
print(f"{seconds} seconds is equal to {hours} hours, {minutes} minutes, and {remaining_seconds} seconds.")