# -*- coding: utf-8 -*-
"""toss.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z0DDBns1cBR8bPyGlOsi3zPZUf1Tpjts

simultate a toss
"""

import random

toss = random.randint(0, 1)
if toss == 0:
    print("Heads")
else:
    print("Tails")