# -*- coding: utf-8 -*-
"""transposematrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RKwE0xqXc2XFEshkKqv9lxD56kWyjlV8

**Transpose of a Matrix**
"""

matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
transpose = [[row[i] for row in matrix] for i in range(len(matrix[0]))]
print("Transpose of the matrix:")
for row in transpose:
    print(row)