# -*- coding: utf-8 -*-
"""tuple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l1rBKK2sRwCzkVF8DCGzWMXIdZr1vozA

tuple

creating a list
"""

coordinates=(10,20,30)
coordinates

"""Accessing items in tuple"""

print(coordinates[0])