# -*- coding: utf-8 -*-
"""tuple2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tMhL4K04nz2ip4xDxGaiV8rUXk8sIvzw
"""

fruit={}
def addone(index):
    if index in fruit:
        fruit[index]+=1
    else:
        fruit[index]=1
addone('Apple')
addone('Banana')
addone('apple')
print(len(fruit))