# -*- coding: utf-8 -*-
"""tuple1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GwSzj5nzwS6naulqk93jaOloBBuLTgc-
"""

init_tuple=('python')*3
print(type(init_tuple))