# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19pu4oKFn5L-rNrzxnX8j82LhiKV-eA1p

**remove duplicates from a list**
"""

numbers = list(map(int, input("Enter numbers separated by space: ").split()))
unique_numbers = list(set(numbers))
print("List without duplicates:", unique_numbers)