# -*- coding: utf-8 -*-
"""Vowel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AJ_pTHiKOHQC_g0KsK8xBMK24pvMqIg7

To check character is a vowel
"""

char=input('enter a character:')
if char in ['a','e','i','o','u']:
    print(f'{char} is a vowel.')
else:
    print(f'{char} is not a vowel')