# -*- coding: utf-8 -*-
"""with.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17vROTkcXy0qTIzMVnJ9EeomIkyUvuU1g

using with statemants
"""

file=open("/content/example.txt","a")
file.write("this is an append line.\n")
file.close()