# -*- coding: utf-8 -*-
"""writingfile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11vHTxAIFGAYQzaFDVP72NSAakWS6HumW

writing to a file
"""

file=open("/content/example.txt","w")
file.write("hello,world!\n")
file.close()